name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck
        run: shellcheck bin/update-wordlists.sh || true
      - name: Smoke test (dry-run, no system scan)
        run: bash tests/smoke_test.sh
